#!/usr/bin/env python3

import urllib.parse
import urllib.request
import urllib.error
import os
import json
import datetime

home = os.getenv('HOME')

with open(os.path.join(home, '.timesync'), 'r') as config:
    config = json.load(config)

    project = input('Project: ')
    activities = [input('Activity: ')]
    while(input('More activities? [y/n] ') == 'y'):
        activities.append(input('Activity: '))

    duration = int(input('Time worked in minutes: '))
    issue_uri = input('Issue uri: ') or None
    d = datetime.datetime.now()
    date_worked = "{}-{}-{}".format(d.year, d.month, d.day)

    # can't choose a custom date or note, sorry
    # pull requests welcome

    url = "{}/v1/times".format(config['server'])
    values = {
        'auth': {
            'username': config['username'],
            'password': config['password'],
        },
        'object': {
            'duration': duration,
            'user': config['username'],
            'project': project,
            'activities': activities,
            'issue_uri': issue_uri,
            'date_worked': date_worked
        }
    }

    data = json.dumps(values)
    data = str.encode(data)

    req = urllib.request.Request(
        url, data, {'Content-Type': 'application/json'})

    try:
        with urllib.request.urlopen(req) as response:
            print("Time successfully recorded!")
    except urllib.error.HTTPError as e:
        error_message = e.read()
        print(error_message)
    except urllib.error.URLError as e:
        print("Cannot connect to server!")
